### ISSUE TITLE
El-astrals Setup guide and troubleshoot. / might be thousands of misspellings but yolo

### ISSUE THREAD

**Issue by pyllyvanukas** [Elli-tt/el-plugins#30]
Make sure you have added all 3 resptories for needed plugins:
### illumineawake - botutils and iutils
owner: illumineawake
name: illu-plugins

### owain94 - chinbreakhandler
owner: owain94
name: openosrs-external-plugins-hosting

### https://github.com/Elli-tt/el-plugins - all plugins u want from our god elliott.
Github Repository owner: Elli-tt
Github Repository name: el-plugins

 

**Check all the plugins are on lates update, (check the plugin on your sidebar and external manager folder that they have same version of the plugin, as seen in picture in below**

![image](https://user-images.githubusercontent.com/62558948/97323974-feceb080-1879-11eb-9ff9-14038052f249.png)
![image](https://user-images.githubusercontent.com/62558948/97324116-2aea3180-187a-11eb-9471-7b63dedc31ad.png)
![image](https://user-images.githubusercontent.com/62558948/97324179-38072080-187a-11eb-8b5c-ce2779e0d0d6.png)

### CONFIG
_**General config**_
_>Use giant pouch [x ] - If u wanna use giant pouch or not_
_>Use Daeyalt Essence [ ] - If u wanna use dayealt essence_
_>Dream mentor completed [x] -If u have completed dream mentor and u are able to use the most eastern bank booth._
_>No Staminas [ ] - If u dont wanna use stamina pots._
_Minium Energy - minium energy% it drink dose of stamina_
_Food ID - ID of the food u want it to use, default 7946 is monkfish_
_>Minium health - Minium health before it eats the set food._

_**DELAY CONFIG**_
_>Dont touch these if u dont know what u are doing. Works fine with default delays._

_**UI Config**_
_>Enable UI [x] - enable the UI for plugin for some information._
_>Pause health - If u run out of food and the hp goes below said value, plugin stops._
![image](https://user-images.githubusercontent.com/62558948/97330054-6d167180-1880-11eb-8830-aa2f1b4095b8.png)

### Client:

Make sure you are in **resizable mode.**
![image](https://user-images.githubusercontent.com/62558948/97331941-989a5b80-1882-11eb-8a17-af09739b404b.png)

### Location:
Make sure you are next to the Moonclan bank, all needed items in invent and u have to enter your bank pin atleast once **IF** its enabled. Or use owain bank pin plugin.
![image](https://user-images.githubusercontent.com/62558948/97325735-f6777500-187b-11eb-9b6e-cbe528424d30.png)
### Items required: Inventory

_**Small, Medium and Large Essence Pouches.**_
**Optional: Giant essence pouch.** OPTIONAL - you can enable it from plugin config.
A Rune pouch containing: Astrals, Laws and Cosmic runes (10k each lasts for ages).
### **_Equipment_**

Weapon:**Dust Batllestaff** (unlimited runes)
Amulet:**Seal of passage** (if dream mentor not completed, so u are able to bank)
Optiona: **Gracefull outfit** for less run % usage, some good shield to take less damage from suqahs (DFS or something, but it makes u use bit more stam potions)

### **_Bank_**

Make sure you remove the placeholders for your essence pouches and rune pouch.
Make sure your bank is full. Otherwise plugin sometimes deposits pouches to bank and gets stuck, filling bank and removing placeholders removes that possibility.

![image](https://user-images.githubusercontent.com/62558948/97326863-18252c00-187d-11eb-9bf9-674139697d14.png)

**Stamina Potions (1).** (1) dose staminas for the run energy recovery.
**Food of your choice.** Default in in cofig is monfish, so get em if u dont wanna change any settings. U can get the other food ID with developer tool or from the internet using sites like https://www.osrsbox.com/tools/item-search/
**Abyssal Book from the Dark Mage.** >makes the NPC contact dialogue shorter and its needed for the plugin to work, u also need to contact dark mage once manually before plugin can do it, since it uses the >visit last option 
![image](https://user-images.githubusercontent.com/62558948/97327774-faa49200-187d-11eb-991f-0bac36a13f20.png)

![image](https://user-images.githubusercontent.com/62558948/97327982-34759880-187e-11eb-8c31-827197ac6569.png)
This is the inventory / bank setup wich u need to run plugin, u dont need own tab for items in the bank, i just have em on single tab to make it easier. Before launching the plugin just open the >ALL BANK TAB and scroll bank to the top, also make sure the withdraw quantity is set as 1 and not ALL or something else.
GIF below shows how it fixes the rune pouch and how the working plugins looks like (yes i know u saw my current rsn in the dialogue, if u report me im gonna stop playing with ur dads testicles 💯, and ur daddy doesent want that )
https://giphy.com/gifs/2a329z5FgcarVHoHWU

### TROUBLESHOOTING COMMON PROBLEMS
1. Sometimes it gets stuck trying to bank next to the astral altar (Reason for this to happen is 95% of the time small lag, atm if the plugin tries to do said action (example teleport to moonclan) and the server lags and it doesent go throught, plugins moves automaticly to the next step, wich would be banking, but since u didnt teleport it just stand next to altar trying to bank
**FIX FOR THIS:** Use low latency worlds, dont download anything while u are using the plugin, mostly lag fucks it up.

2. Sometimes deposits whole inventory trying to fix the essence pouches
**FIX FOR THIS:** Before starting the plugin, remove placeholders for RUNEPOUCH and ALL 3or4 ESSENCE POUCHES and make ur bank full with the fillers (seen in step above in bank section) This way its impossible to bank anything to bank wich doesent have placeholder

3. Sometimes it gets ''stuck'' for small period of time in spot shown below, 99% of the time it doesent get stuck there more than 2-3 seconds, but sometimes it might stand there for 10 seconds or so, and u are getting usually molested by the suqah
**JUST A NOTE FOR LOWER COMBAT LVL / HP LEVEL ACCOUNTS THAT U MIGHT GET MOLESTED BY THE SUQAH IN THIS LOCATION**
![image](https://user-images.githubusercontent.com/62558948/97329779-1c9f1400-1880-11eb-9ec2-429f48617f29.png)

For more advanced tips and tricks u might wanna join the discord servers and ask big boys for help, but please try and fix the problem atleast once or twice by urself before DM'ing mods and asking for help.
People are allways happy to help, but spoonfeeding most pepega people gets boring real quick 💯.

https://discord.gg/ckKN2PD - Discord for mainly Elliott's plugins
https://discord.gg/auBQCDH - Illumine's cox and ball torture dungeon. (Very nice server with loads of good looking osrs players.)
https://discord.gg/NDkPdw7 - Owain's discord (support for break handler and stuff)

### **_CREDITS_**
All kudos goes to the all the contributors and wonderful people working with these plugins for free.
Owain94
Illumine
Elliott
❤️

**Comment by Elli-tt** [comment]
added to wiki 👍
